name: CI Pipeline

# Se ejecuta cuando se hace push a la rama main o pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el codigo del repositorio
    - name: Check out code
      uses: actions/checkout@v4

    # 2. Instalar uv (el gestor de paquetes rapido que usas)
    - name: Install uv
      uses: astral-sh/setup-uv@v1

    # 3. Configurar Python usando uv
    - name: Set up Python
      run: uv python install 3.12.4

   # 1. INSTALAR las dependencias
    - name: Install dependencies
      run: make install

    # 2. REFACTOR: Formato + Linting (Usa 'make refactor')
    - name: Check Code Quality (Format & Lint)
      run: make refactor

    # 3. TEST (Usa 'make test')
    - name: Run Tests
      run: make test

